

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
// 
// Do not make changes directly to this file - edit the template instead.
// 
// The following connection settings were used to generate this file:
//     Configuration file:     "Rdp.Data\app.config"
//     Connection String Name: "MyDbContext"
//     Connection String:      "Data Source=10.200.253.168;Initial Catalog=TMQ4;persist security info=True;user id=sa;password=**zapped**;;application name=MyDbContext"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Enterprise Edition: Core-based Licensing (64-bit)
// Database Engine Edition: Enterprise

using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Rdp.Core.Data;

namespace Rdp.Data.Entity
{
}
// </auto-generated>














