//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdp.Resources.Globalization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResButton {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResButton() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rdp.Resources.Globalization.ResButton", typeof(ResButton).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 按钮 的本地化字符串。
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮样式 的本地化字符串。
        /// </summary>
        public static string ButtonClass {
            get {
                return ResourceManager.GetString("ButtonClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮数据 的本地化字符串。
        /// </summary>
        public static string ButtonDataOptions {
            get {
                return ResourceManager.GetString("ButtonDataOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮链接 的本地化字符串。
        /// </summary>
        public static string ButtonHref {
            get {
                return ResourceManager.GetString("ButtonHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮图标 的本地化字符串。
        /// </summary>
        public static string ButtonIcon {
            get {
                return ResourceManager.GetString("ButtonIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮编号 的本地化字符串。
        /// </summary>
        public static string ButtonID {
            get {
                return ResourceManager.GetString("ButtonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮名称 的本地化字符串。
        /// </summary>
        public static string ButtonName {
            get {
                return ResourceManager.GetString("ButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮脚本 的本地化字符串。
        /// </summary>
        public static string ButtonScript {
            get {
                return ResourceManager.GetString("ButtonScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示文本 的本地化字符串。
        /// </summary>
        public static string ButtonText {
            get {
                return ResourceManager.GetString("ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮排序 的本地化字符串。
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效性 的本地化字符串。
        /// </summary>
        public static string StatusFlag {
            get {
                return ResourceManager.GetString("StatusFlag", resourceCulture);
            }
        }
    }
}
