//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdp.Resources.Globalization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResBranch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResBranch() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rdp.Resources.Globalization.ResBranch", typeof(ResBranch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 分店所属公司 的本地化字符串。
        /// </summary>
        public static string AgentCode {
            get {
                return ResourceManager.GetString("AgentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小区 的本地化字符串。
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小区描述 的本地化字符串。
        /// </summary>
        public static string AreaDescription {
            get {
                return ResourceManager.GetString("AreaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店铺组成 的本地化字符串。
        /// </summary>
        public static string BoothType {
            get {
                return ResourceManager.GetString("BoothType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分店 的本地化字符串。
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分店编号 的本地化字符串。
        /// </summary>
        public static string BranchCode {
            get {
                return ResourceManager.GetString("BranchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分店名称 的本地化字符串。
        /// </summary>
        public static string BranchDescription {
            get {
                return ResourceManager.GetString("BranchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分店范围 的本地化字符串。
        /// </summary>
        public static string BranchGroup {
            get {
                return ResourceManager.GetString("BranchGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分店范围描述 的本地化字符串。
        /// </summary>
        public static string BranchGroupDesc {
            get {
                return ResourceManager.GetString("BranchGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单据显示名称 的本地化字符串。
        /// </summary>
        public static string BranchLong {
            get {
                return ResourceManager.GetString("BranchLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单据显示地址 的本地化字符串。
        /// </summary>
        public static string BriefAddress {
            get {
                return ResourceManager.GetString("BriefAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属商圈 的本地化字符串。
        /// </summary>
        public static string CBDCode {
            get {
                return ResourceManager.GetString("CBDCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分店城市 的本地化字符串。
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分店城市 的本地化字符串。
        /// </summary>
        public static string CityDescription {
            get {
                return ResourceManager.GetString("CityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 城市等级 的本地化字符串。
        /// </summary>
        public static string CityLevel {
            get {
                return ResourceManager.GetString("CityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 城市等级描述 的本地化字符串。
        /// </summary>
        public static string CityLevelDescription {
            get {
                return ResourceManager.GetString("CityLevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每日关店时间 的本地化字符串。
        /// </summary>
        public static string CloseTime {
            get {
                return ResourceManager.GetString("CloseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 POS店標示位 的本地化字符串。
        /// </summary>
        public static string CobolMergeCode {
            get {
                return ResourceManager.GetString("CobolMergeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属公司 的本地化字符串。
        /// </summary>
        public static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 县 的本地化字符串。
        /// </summary>
        public static string County {
            get {
                return ResourceManager.GetString("County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 县描述 的本地化字符串。
        /// </summary>
        public static string CountyDescription {
            get {
                return ResourceManager.GetString("CountyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域编号 的本地化字符串。
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分店区域 的本地化字符串。
        /// </summary>
        public static string DistrictDesc {
            get {
                return ResourceManager.GetString("DistrictDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结业日期 的本地化字符串。
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pos店的IP地址 的本地化字符串。
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微小区代码 的本地化字符串。
        /// </summary>
        public static string MiniArea {
            get {
                return ResourceManager.GetString("MiniArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微小区描述 的本地化字符串。
        /// </summary>
        public static string MiniAreaDesc {
            get {
                return ResourceManager.GetString("MiniAreaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收款方式 的本地化字符串。
        /// </summary>
        public static string PayModeDesc {
            get {
                return ResourceManager.GetString("PayModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分店省份 的本地化字符串。
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分店省份 的本地化字符串。
        /// </summary>
        public static string ProvinceDescription {
            get {
                return ResourceManager.GetString("ProvinceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否打卡 的本地化字符串。
        /// </summary>
        public static string ReaderType {
            get {
                return ResourceManager.GetString("ReaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源行号 的本地化字符串。
        /// </summary>
        public static string RefBranchCode {
            get {
                return ResourceManager.GetString("RefBranchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源行描述 的本地化字符串。
        /// </summary>
        public static string RefBranchDesc {
            get {
                return ResourceManager.GetString("RefBranchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源行结业时间 的本地化字符串。
        /// </summary>
        public static string RefBranchEndDate {
            get {
                return ResourceManager.GetString("RefBranchEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源行开业时间 的本地化字符串。
        /// </summary>
        public static string RefBranchStartDate {
            get {
                return ResourceManager.GetString("RefBranchStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控股比例 的本地化字符串。
        /// </summary>
        public static string Shareholding {
            get {
                return ResourceManager.GetString("Shareholding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存货级别 的本地化字符串。
        /// </summary>
        public static string ShopScale {
            get {
                return ResourceManager.GetString("ShopScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分店性质 的本地化字符串。
        /// </summary>
        public static string ShopType {
            get {
                return ResourceManager.GetString("ShopType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小小区代码 的本地化字符串。
        /// </summary>
        public static string SmallArea {
            get {
                return ResourceManager.GetString("SmallArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小小区描述 的本地化字符串。
        /// </summary>
        public static string SmallAreaDesc {
            get {
                return ResourceManager.GetString("SmallAreaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开业日期 的本地化字符串。
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于自动配货分组 的本地化字符串。
        /// </summary>
        public static string StoreGroup {
            get {
                return ResourceManager.GetString("StoreGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 開票公司（批发环节） 的本地化字符串。
        /// </summary>
        public static string TeamCode {
            get {
                return ResourceManager.GetString("TeamCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话号码 的本地化字符串。
        /// </summary>
        public static string TelephoneNo {
            get {
                return ResourceManager.GetString("TelephoneNo", resourceCulture);
            }
        }
    }
}
