//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdp.Resources.Globalization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResError() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rdp.Resources.Globalization.ResError", typeof(ResError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 访问出错,请联系管理员! 的本地化字符串。
        /// </summary>
        public static string ErrDesc {
            get {
                return ResourceManager.GetString("ErrDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会话过期,请重新登陆! 的本地化字符串。
        /// </summary>
        public static string ErrDesc1 {
            get {
                return ResourceManager.GetString("ErrDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取IP失败,请联系管理员! 的本地化字符串。
        /// </summary>
        public static string ErrDesc2 {
            get {
                return ResourceManager.GetString("ErrDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无分行可以进行登陆! 的本地化字符串。
        /// </summary>
        public static string ErrDesc3 {
            get {
                return ResourceManager.GetString("ErrDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接服务器失败,请联系管理员! 的本地化字符串。
        /// </summary>
        public static string ErrDesc4 {
            get {
                return ResourceManager.GetString("ErrDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无权访问该页面! 的本地化字符串。
        /// </summary>
        public static string ErrDesc5 {
            get {
                return ResourceManager.GetString("ErrDesc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到网页! 的本地化字符串。
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭本页面 的本地化字符串。
        /// </summary>
        public static string QuickClose {
            get {
                return ResourceManager.GetString("QuickClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速跳转 的本地化字符串。
        /// </summary>
        public static string QuickJump {
            get {
                return ResourceManager.GetString("QuickJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (注: 5秒后,页面会自动关闭) 的本地化字符串。
        /// </summary>
        public static string Remark1 {
            get {
                return ResourceManager.GetString("Remark1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (注: 5秒后,页面会自动跳转) 的本地化字符串。
        /// </summary>
        public static string Remark2 {
            get {
                return ResourceManager.GetString("Remark2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;h2&gt;系统错误：&lt;/h2&gt;&lt;hr/&gt;系统发生错误，错误编号为： 的本地化字符串。
        /// </summary>
        public static string SystemError1 {
            get {
                return ResourceManager.GetString("SystemError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 。该信息已被系统记录，请稍后重试或与系统管理员联系。&lt;br/&gt;错误地址： 的本地化字符串。
        /// </summary>
        public static string SystemError2 {
            get {
                return ResourceManager.GetString("SystemError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;br/&gt;错误信息： &lt;font class=&quot;&quot;ErrorMessage&quot;&quot;&gt; 的本地化字符串。
        /// </summary>
        public static string SystemError3 {
            get {
                return ResourceManager.GetString("SystemError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温馨提示 的本地化字符串。
        /// </summary>
        public static string Tooltip {
            get {
                return ResourceManager.GetString("Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统温馨提示您: 的本地化字符串。
        /// </summary>
        public static string Tooltip1 {
            get {
                return ResourceManager.GetString("Tooltip1", resourceCulture);
            }
        }
    }
}
