//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdp.Resources.Globalization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResIndex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResIndex() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rdp.Resources.Globalization.ResIndex", typeof(ResIndex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统首页 的本地化字符串。
        /// </summary>
        public static string BackIndex {
            get {
                return ResourceManager.GetString("BackIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        public static string Cancellation {
            get {
                return ResourceManager.GetString("Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择登录账号 的本地化字符串。
        /// </summary>
        public static string ChoiceAccount {
            get {
                return ResourceManager.GetString("ChoiceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加到收藏夹 的本地化字符串。
        /// </summary>
        public static string Collect {
            get {
                return ResourceManager.GetString("Collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制面板 的本地化字符串。
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rdp管理系统 的本地化字符串。
        /// </summary>
        public static string COU {
            get {
                return ResourceManager.GetString("COU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户关系管理系统 的本地化字符串。
        /// </summary>
        public static string CRM {
            get {
                return ResourceManager.GetString("CRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;font color=red style=&quot;font-size:14px;font-weight:bold;&quot;&gt;密码已到期，如不修改，明天将无法登录！&lt;/font&gt; 的本地化字符串。
        /// </summary>
        public static string Expiry {
            get {
                return ResourceManager.GetString("Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅供学习研究 的本地化字符串。
        /// </summary>
        public static string FooterInfo {
            get {
                return ResourceManager.GetString("FooterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作指引 的本地化字符串。
        /// </summary>
        public static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统首页 的本地化字符串。
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入卡号 的本地化字符串。
        /// </summary>
        public static string InputCardNo {
            get {
                return ResourceManager.GetString("InputCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入礼券号码 的本地化字符串。
        /// </summary>
        public static string InputCouponNum {
            get {
                return ResourceManager.GetString("InputCouponNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载中,请稍等…… 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rdp管理系统 - 登录首页 的本地化字符串。
        /// </summary>
        public static string LoginIndex {
            get {
                return ResourceManager.GetString("LoginIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有权限进入本页！\\n请重新登录或与管理员联系 的本地化字符串。
        /// </summary>
        public static string LoginOut {
            get {
                return ResourceManager.GetString("LoginOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看所有信息 的本地化字符串。
        /// </summary>
        public static string LookOverALLInformation {
            get {
                return ResourceManager.GetString("LookOverALLInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看详情 的本地化字符串。
        /// </summary>
        public static string LookOverDetails {
            get {
                return ResourceManager.GetString("LookOverDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理員 的本地化字符串。
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string ModifyPassword {
            get {
                return ResourceManager.GetString("ModifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航 的本地化字符串。
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不可以被关闭 的本地化字符串。
        /// </summary>
        public static string NoClose {
            get {
                return ResourceManager.GetString("NoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作指引 的本地化字符串。
        /// </summary>
        public static string OperatingInstructions {
            get {
                return ResourceManager.GetString("OperatingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码修改 的本地化字符串。
        /// </summary>
        public static string PasswordChanges {
            get {
                return ResourceManager.GetString("PasswordChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相关问题 的本地化字符串。
        /// </summary>
        public static string RelatedQuestions {
            get {
                return ResourceManager.GetString("RelatedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码还有&lt;font color=red style=&quot;font-size:14px;font-weight:bold;&quot;&gt; 的本地化字符串。
        /// </summary>
        public static string RemainderDays1 {
            get {
                return ResourceManager.GetString("RemainderDays1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/font&gt;天到期，请尽快修改。 的本地化字符串。
        /// </summary>
        public static string RemainderDays2 {
            get {
                return ResourceManager.GetString("RemainderDays2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找回密码 的本地化字符串。
        /// </summary>
        public static string RetrievePassword {
            get {
                return ResourceManager.GetString("RetrievePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 皮肤 的本地化字符串。
        /// </summary>
        public static string Skin {
            get {
                return ResourceManager.GetString("Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温馨提示 的本地化字符串。
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加快捷方式 的本地化字符串。
        /// </summary>
        public static string toDesktop {
            get {
                return ResourceManager.GetString("toDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前IE安全级别不允许操作！请设置后在操作。 的本地化字符串。
        /// </summary>
        public static string toDesktopFail {
            get {
                return ResourceManager.GetString("toDesktopFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经在桌面上生成快捷方式 的本地化字符串。
        /// </summary>
        public static string toDesktopSuccess {
            get {
                return ResourceManager.GetString("toDesktopSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://10.200.252.85 的本地化字符串。
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户注册 的本地化字符串。
        /// </summary>
        public static string UserRegistration {
            get {
                return ResourceManager.GetString("UserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待验收礼券 的本地化字符串。
        /// </summary>
        public static string WaitAcceptanceCoupon {
            get {
                return ResourceManager.GetString("WaitAcceptanceCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待更新 的本地化字符串。
        /// </summary>
        public static string WaitforUpdate {
            get {
                return ResourceManager.GetString("WaitforUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用Rdp示例系统，有关系统的任何操作问题请查阅以下內容 的本地化字符串。
        /// </summary>
        public static string WarmTips {
            get {
                return ResourceManager.GetString("WarmTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎您 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作单 的本地化字符串。
        /// </summary>
        public static string WorkOrder {
            get {
                return ResourceManager.GetString("WorkOrder", resourceCulture);
            }
        }
    }
}
