//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdp.Resources.Globalization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResMessage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rdp.Resources.Globalization.ResMessage", typeof(ResMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 账号无效 的本地化字符串。
        /// </summary>
        public static string AccountInvaliable {
            get {
                return ResourceManager.GetString("AccountInvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号不存在 的本地化字符串。
        /// </summary>
        public static string AccountNotExist {
            get {
                return ResourceManager.GetString("AccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起用时间不能延后，到期时间不能提前 的本地化字符串。
        /// </summary>
        public static string BeginTimeNotDelayAndEndTimeNotAhead {
            get {
                return ResourceManager.GetString("BeginTimeNotDelayAndEndTimeNotAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分店不存在 的本地化字符串。
        /// </summary>
        public static string BranchNoExist {
            get {
                return ResourceManager.GetString("BranchNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能前大于后 的本地化字符串。
        /// </summary>
        public static string CannotGreaterThanFormer {
            get {
                return ResourceManager.GetString("CannotGreaterThanFormer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统最多只能导出5万条记录，如超出5万条请下单抽取 的本地化字符串。
        /// </summary>
        public static string CanOnlyExport50000RecordsPleaseExtract {
            get {
                return ResourceManager.GetString("CanOnlyExport50000RecordsPleaseExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡等级需黄金及以上级别 的本地化字符串。
        /// </summary>
        public static string CardLevelLimit {
            get {
                return ResourceManager.GetString("CardLevelLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡号无效或不存在 的本地化字符串。
        /// </summary>
        public static string CardNoInvaliable {
            get {
                return ResourceManager.GetString("CardNoInvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是有效的会员卡片 的本地化字符串。
        /// </summary>
        public static string CardRecordInvaliable {
            get {
                return ResourceManager.GetString("CardRecordInvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 礼券 的本地化字符串。
        /// </summary>
        public static string Coupon {
            get {
                return ResourceManager.GetString("Coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不在当前分店礼券 的本地化字符串。
        /// </summary>
        public static string CouponNotInCurrentBranch {
            get {
                return ResourceManager.GetString("CouponNotInCurrentBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字母(2位以上)+数字 的本地化字符串。
        /// </summary>
        public static string CouponNumFormat {
            get {
                return ResourceManager.GetString("CouponNumFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期格式错误 的本地化字符串。
        /// </summary>
        public static string DateInValid {
            get {
                return ResourceManager.GetString("DateInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在不可销售状态礼券 的本地化字符串。
        /// </summary>
        public static string DoNotSales {
            get {
                return ResourceManager.GetString("DoNotSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在礼券不可使用 的本地化字符串。
        /// </summary>
        public static string DoNotUse {
            get {
                return ResourceManager.GetString("DoNotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误描述 的本地化字符串。
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误代号 的本地化字符串。
        /// </summary>
        public static string ErrorNo {
            get {
                return ResourceManager.GetString("ErrorNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在 的本地化字符串。
        /// </summary>
        public static string Exist {
            get {
                return ResourceManager.GetString("Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已过期 的本地化字符串。
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第一张券 的本地化字符串。
        /// </summary>
        public static string FirstCoupon {
            get {
                return ResourceManager.GetString("FirstCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单 的本地化字符串。
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件不允许存在空值 的本地化字符串。
        /// </summary>
        public static string ImportFileNotExistNullValue {
            get {
                return ResourceManager.GetString("ImportFileNotExistNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件沒有记录 的本地化字符串。
        /// </summary>
        public static string ImportFileNotNull {
            get {
                return ResourceManager.GetString("ImportFileNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加库存 的本地化字符串。
        /// </summary>
        public static string IncreaseStock {
            get {
                return ResourceManager.GetString("IncreaseStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息核对 的本地化字符串。
        /// </summary>
        public static string InformationCheck {
            get {
                return ResourceManager.GetString("InformationCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效 的本地化字符串。
        /// </summary>
        public static string Invaliable {
            get {
                return ResourceManager.GetString("Invaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是会员 的本地化字符串。
        /// </summary>
        public static string IsMember {
            get {
                return ResourceManager.GetString("IsMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加后将不可更改，是否确定添加？ 的本地化字符串。
        /// </summary>
        public static string IsSureToAdd {
            get {
                return ResourceManager.GetString("IsSureToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认取消该单回收吗？ 的本地化字符串。
        /// </summary>
        public static string IsSureToCancelReturn {
            get {
                return ResourceManager.GetString("IsSureToCancelReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认取消该单销售吗？ 的本地化字符串。
        /// </summary>
        public static string IsSureToCancelSale {
            get {
                return ResourceManager.GetString("IsSureToCancelSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除吗？ 的本地化字符串。
        /// </summary>
        public static string IsSureToDelete {
            get {
                return ResourceManager.GetString("IsSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后一张券 的本地化字符串。
        /// </summary>
        public static string LastCoupon {
            get {
                return ResourceManager.GetString("LastCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后 的本地化字符串。
        /// </summary>
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码已注册 的本地化字符串。
        /// </summary>
        public static string MobilePhoneExist {
            get {
                return ResourceManager.GetString("MobilePhoneExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码可用 的本地化字符串。
        /// </summary>
        public static string MobilePhoneNoExist {
            get {
                return ResourceManager.GetString("MobilePhoneNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于 的本地化字符串。
        /// </summary>
        public static string MoreThan {
            get {
                return ResourceManager.GetString("MoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少选择一项 的本地化字符串。
        /// </summary>
        public static string MoreThanSelectOne {
            get {
                return ResourceManager.GetString("MoreThanSelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 礼券不在当前分店 的本地化字符串。
        /// </summary>
        public static string NoInCurrentBranch {
            get {
                return ResourceManager.GetString("NoInCurrentBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有搜索到相关记录 的本地化字符串。
        /// </summary>
        public static string NoMatchData {
            get {
                return ResourceManager.GetString("NoMatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有权限操作 的本地化字符串。
        /// </summary>
        public static string NoRight {
            get {
                return ResourceManager.GetString("NoRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在 的本地化字符串。
        /// </summary>
        public static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能少于0 的本地化字符串。
        /// </summary>
        public static string NotLessThan0 {
            get {
                return ResourceManager.GetString("NotLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能为空 的本地化字符串。
        /// </summary>
        public static string NotNull {
            get {
                return ResourceManager.GetString("NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不可销售 的本地化字符串。
        /// </summary>
        public static string NotSales {
            get {
                return ResourceManager.GetString("NotSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行号 的本地化字符串。
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原值 的本地化字符串。
        /// </summary>
        public static string OldValue {
            get {
                return ResourceManager.GetString("OldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入数据应属于同一位客户！ 的本地化字符串。
        /// </summary>
        public static string OnlyCustomerTips {
            get {
                return ResourceManager.GetString("OnlyCustomerTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作结果 的本地化字符串。
        /// </summary>
        public static string OperationResult {
            get {
                return ResourceManager.GetString("OperationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或 的本地化字符串。
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分 的本地化字符串。
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误 的本地化字符串。
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码过期 的本地化字符串。
        /// </summary>
        public static string PasswordExpired {
            get {
                return ResourceManager.GetString("PasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请 的本地化字符串。
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请添加文件到预览 的本地化字符串。
        /// </summary>
        public static string PleaseAddToPreview {
            get {
                return ResourceManager.GetString("PleaseAddToPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        public static string PleaseChoose {
            get {
                return ResourceManager.GetString("PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择文件 的本地化字符串。
        /// </summary>
        public static string PleaseChooseFile {
            get {
                return ResourceManager.GetString("PleaseChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入 的本地化字符串。
        /// </summary>
        public static string PleaseEnter {
            get {
                return ResourceManager.GetString("PleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入数字 的本地化字符串。
        /// </summary>
        public static string PleaseEnterNum {
            get {
                return ResourceManager.GetString("PleaseEnterNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入1至99的数字 的本地化字符串。
        /// </summary>
        public static string PleaseEnterNumFrom1to99 {
            get {
                return ResourceManager.GetString("PleaseEnterNumFrom1to99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入有效金额 的本地化字符串。
        /// </summary>
        public static string PleaseEnterValidAmount {
            get {
                return ResourceManager.GetString("PleaseEnterValidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请导出错误反馈表查看 的本地化字符串。
        /// </summary>
        public static string PleaseExportErrorExcel {
            get {
                return ResourceManager.GetString("PleaseExportErrorExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先获取验证码 的本地化字符串。
        /// </summary>
        public static string PleaseGetVerificationCode {
            get {
                return ResourceManager.GetString("PleaseGetVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入礼券编号范围 的本地化字符串。
        /// </summary>
        public static string PleaseInputRange {
            get {
                return ResourceManager.GetString("PleaseInputRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 随机码最大限制为3位 的本地化字符串。
        /// </summary>
        public static string RandomLengthLimit3 {
            get {
                return ResourceManager.GetString("RandomLengthLimit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 范围 的本地化字符串。
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍卡验证 的本地化字符串。
        /// </summary>
        public static string ReadCardVerification {
            get {
                return ResourceManager.GetString("ReadCardVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重定向到指定页面 的本地化字符串。
        /// </summary>
        public static string RedirectUrl {
            get {
                return ResourceManager.GetString("RedirectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已注册 的本地化字符串。
        /// </summary>
        public static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必填资料 的本地化字符串。
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行数 的本地化字符串。
        /// </summary>
        public static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已奖赏 的本地化字符串。
        /// </summary>
        public static string Saled {
            get {
                return ResourceManager.GetString("Saled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售单号为0~20位有效数字 的本地化字符串。
        /// </summary>
        public static string SaleOrderNoLength20 {
            get {
                return ResourceManager.GetString("SaleOrderNoLength20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售单列印 的本地化字符串。
        /// </summary>
        public static string SalesOrderPrint {
            get {
                return ResourceManager.GetString("SalesOrderPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售单未分配礼券或分配超额 的本地化字符串。
        /// </summary>
        public static string SalesOrderUnDistributionOrExcess {
            get {
                return ResourceManager.GetString("SalesOrderUnDistributionOrExcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一条数据 的本地化字符串。
        /// </summary>
        public static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置不可重复 的本地化字符串。
        /// </summary>
        public static string SettingNotRepeatable {
            get {
                return ResourceManager.GetString("SettingNotRepeatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货架二维码 的本地化字符串。
        /// </summary>
        public static string ShelvesQrcode {
            get {
                return ResourceManager.GetString("ShelvesQrcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有该域名的权限! 的本地化字符串。
        /// </summary>
        public static string SiteTips {
            get {
                return ResourceManager.GetString("SiteTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板表格 的本地化字符串。
        /// </summary>
        public static string TemplateForm {
            get {
                return ResourceManager.GetString("TemplateForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转移礼券数量 的本地化字符串。
        /// </summary>
        public static string TransferCouponNum {
            get {
                return ResourceManager.GetString("TransferCouponNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已使用 的本地化字符串。
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请使用IE浏览器 的本地化字符串。
        /// </summary>
        public static string UseIE {
            get {
                return ResourceManager.GetString("UseIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户ID验证 的本地化字符串。
        /// </summary>
        public static string UserCodeVerification {
            get {
                return ResourceManager.GetString("UserCodeVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码验证 的本地化字符串。
        /// </summary>
        public static string UserPasswordVerification {
            get {
                return ResourceManager.GetString("UserPasswordVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效 的本地化字符串。
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证不通过 的本地化字符串。
        /// </summary>
        public static string ValidNotThrough {
            get {
                return ResourceManager.GetString("ValidNotThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码校验 的本地化字符串。
        /// </summary>
        public static string VerificationCodeCheck {
            get {
                return ResourceManager.GetString("VerificationCodeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码不正确，请重新输入 的本地化字符串。
        /// </summary>
        public static string VerificationCodeIsIncorrectPleaseReInput {
            get {
                return ResourceManager.GetString("VerificationCodeIsIncorrectPleaseReInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码最大限制为4位 的本地化字符串。
        /// </summary>
        public static string VerificationCodeLengthLimit4 {
            get {
                return ResourceManager.GetString("VerificationCodeLengthLimit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码输入正确 的本地化字符串。
        /// </summary>
        public static string VerificationCodeRight {
            get {
                return ResourceManager.GetString("VerificationCodeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不正确 的本地化字符串。
        /// </summary>
        public static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式错误 的本地化字符串。
        /// </summary>
        public static string WrongFormat {
            get {
                return ResourceManager.GetString("WrongFormat", resourceCulture);
            }
        }
    }
}
