//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdp.Resources.Globalization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResPrivilege {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResPrivilege() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rdp.Resources.Globalization.ResPrivilege", typeof(ResPrivilege).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 程序或按钮或分店 的本地化字符串。
        /// </summary>
        public static string AccessMaster {
            get {
                return ResourceManager.GetString("AccessMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        public static string AccessValue {
            get {
                return ResourceManager.GetString("AccessValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分店范围 的本地化字符串。
        /// </summary>
        public static string BranchMember {
            get {
                return ResourceManager.GetString("BranchMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份验证 的本地化字符串。
        /// </summary>
        public static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作权限 的本地化字符串。
        /// </summary>
        public static string OperationID {
            get {
                return ResourceManager.GetString("OperationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户权限 的本地化字符串。
        /// </summary>
        public static string Privilege {
            get {
                return ResourceManager.GetString("Privilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限编号 的本地化字符串。
        /// </summary>
        public static string PrivilegeID {
            get {
                return ResourceManager.GetString("PrivilegeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号或角色 的本地化字符串。
        /// </summary>
        public static string PrivilegeMaster {
            get {
                return ResourceManager.GetString("PrivilegeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        public static string PrivilegeValue {
            get {
                return ResourceManager.GetString("PrivilegeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期 的本地化字符串。
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束日期 的本地化字符串。
        /// </summary>
        public static string ValidUntil {
            get {
                return ResourceManager.GetString("ValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值描述 的本地化字符串。
        /// </summary>
        public static string ValueDesc {
            get {
                return ResourceManager.GetString("ValueDesc", resourceCulture);
            }
        }
    }
}
