//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdp.Resources.Globalization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResSuggest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResSuggest() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rdp.Resources.Globalization.ResSuggest", typeof(ResSuggest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败 的本地化字符串。
        /// </summary>
        public static string AddFail {
            get {
                return ResourceManager.GetString("AddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功 的本地化字符串。
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申请失败 的本地化字符串。
        /// </summary>
        public static string ApplyFail {
            get {
                return ResourceManager.GetString("ApplyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申请成功 的本地化字符串。
        /// </summary>
        public static string ApplySuccess {
            get {
                return ResourceManager.GetString("ApplySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批失败 的本地化字符串。
        /// </summary>
        public static string ApproveFail {
            get {
                return ResourceManager.GetString("ApproveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批成功 的本地化字符串。
        /// </summary>
        public static string ApproveSuccess {
            get {
                return ResourceManager.GetString("ApproveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配失败 的本地化字符串。
        /// </summary>
        public static string AssignFail {
            get {
                return ResourceManager.GetString("AssignFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配成功 的本地化字符串。
        /// </summary>
        public static string AssignSuccess {
            get {
                return ResourceManager.GetString("AssignSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消失败 的本地化字符串。
        /// </summary>
        public static string CancelFail {
            get {
                return ResourceManager.GetString("CancelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消成功 的本地化字符串。
        /// </summary>
        public static string CancelSuccess {
            get {
                return ResourceManager.GetString("CancelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结案失败 的本地化字符串。
        /// </summary>
        public static string ClosureFail {
            get {
                return ResourceManager.GetString("ClosureFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结案成功 的本地化字符串。
        /// </summary>
        public static string ClosureSuccess {
            get {
                return ResourceManager.GetString("ClosureSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        public static string DeleteFail {
            get {
                return ResourceManager.GetString("DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建失败 的本地化字符串。
        /// </summary>
        public static string InsertFail {
            get {
                return ResourceManager.GetString("InsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建成功 的本地化字符串。
        /// </summary>
        public static string InsertSucceed {
            get {
                return ResourceManager.GetString("InsertSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败 的本地化字符串。
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录成功 的本地化字符串。
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        public static string OperateFail {
            get {
                return ResourceManager.GetString("OperateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        public static string OperateSuccess {
            get {
                return ResourceManager.GetString("OperateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        public static string SaveFail {
            get {
                return ResourceManager.GetString("SaveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送失败 的本地化字符串。
        /// </summary>
        public static string SendFail {
            get {
                return ResourceManager.GetString("SendFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送成功 的本地化字符串。
        /// </summary>
        public static string SendSuccess {
            get {
                return ResourceManager.GetString("SendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改失败 的本地化字符串。
        /// </summary>
        public static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功 的本地化字符串。
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级失败 的本地化字符串。
        /// </summary>
        public static string UpGradeFail {
            get {
                return ResourceManager.GetString("UpGradeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级成功 的本地化字符串。
        /// </summary>
        public static string UpGradeSuccess {
            get {
                return ResourceManager.GetString("UpGradeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传失败 的本地化字符串。
        /// </summary>
        public static string UploadFail {
            get {
                return ResourceManager.GetString("UploadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传成功 的本地化字符串。
        /// </summary>
        public static string UploadSuccess {
            get {
                return ResourceManager.GetString("UploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验失败 的本地化字符串。
        /// </summary>
        public static string ValidateFail {
            get {
                return ResourceManager.GetString("ValidateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验成功 的本地化字符串。
        /// </summary>
        public static string ValidateSuccess {
            get {
                return ResourceManager.GetString("ValidateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写卡失败 的本地化字符串。
        /// </summary>
        public static string WriteFail {
            get {
                return ResourceManager.GetString("WriteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写卡成功 的本地化字符串。
        /// </summary>
        public static string WriteSuccess {
            get {
                return ResourceManager.GetString("WriteSuccess", resourceCulture);
            }
        }
    }
}
