//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdp.Resources.Globalization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResUserMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResUserMaster() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rdp.Resources.Globalization.ResUserMaster", typeof(ResUserMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 绑定失败 的本地化字符串。
        /// </summary>
        public static string BindingFail {
            get {
                return ResourceManager.GetString("BindingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定成功 的本地化字符串。
        /// </summary>
        public static string BindingSucceed {
            get {
                return ResourceManager.GetString("BindingSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门编号 的本地化字符串。
        /// </summary>
        public static string BranchCode {
            get {
                return ResourceManager.GetString("BranchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认绑定 的本地化字符串。
        /// </summary>
        public static string ConfirmBinding {
            get {
                return ResourceManager.GetString("ConfirmBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认操作 的本地化字符串。
        /// </summary>
        public static string ConfirmOperate {
            get {
                return ResourceManager.GetString("ConfirmOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rdp管理系统权限开通 的本地化字符串。
        /// </summary>
        public static string COUPriviligeOpen {
            get {
                return ResourceManager.GetString("COUPriviligeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户关系管理系统找回密码 的本地化字符串。
        /// </summary>
        public static string CRMGetPassword {
            get {
                return ResourceManager.GetString("CRMGetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRM密码找回 的本地化字符串。
        /// </summary>
        public static string CRMPasswordRetrieve {
            get {
                return ResourceManager.GetString("CRMPasswordRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRM权限开通 的本地化字符串。
        /// </summary>
        public static string CRMPriviligeOpen {
            get {
                return ResourceManager.GetString("CRMPriviligeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册邮箱 的本地化字符串。
        /// </summary>
        public static string EmailAdd {
            get {
                return ResourceManager.GetString("EmailAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同权限人帐号 的本地化字符串。
        /// </summary>
        public static string EquelPrivilegeUserID {
            get {
                return ResourceManager.GetString("EquelPrivilegeUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工号 的本地化字符串。
        /// </summary>
        public static string FlowbyCode {
            get {
                return ResourceManager.GetString("FlowbyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string FlowbyName {
            get {
                return ResourceManager.GetString("FlowbyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取IP 的本地化字符串。
        /// </summary>
        public static string GetIP {
            get {
                return ResourceManager.GetString("GetIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分店没有CRM权限 的本地化字符串。
        /// </summary>
        public static string HavingNoCRMPermission {
            get {
                return ResourceManager.GetString("HavingNoCRMPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址 的本地化字符串。
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示IP地址 的本地化字符串。
        /// </summary>
        public static string IPAdressView {
            get {
                return ResourceManager.GetString("IPAdressView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆地址： 的本地化字符串。
        /// </summary>
        public static string LoginAddress {
            get {
                return ResourceManager.GetString("LoginAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为确保CRM账号的安全，请查看邮件后及时更改密码！ 的本地化字符串。
        /// </summary>
        public static string LookAndUpdate {
            get {
                return ResourceManager.GetString("LookAndUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码不能与旧密码相同 的本地化字符串。
        /// </summary>
        public static string NewPasswordCannotEquelOldPassword {
            get {
                return ResourceManager.GetString("NewPasswordCannotEquelOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能输入数字或字母 的本地化字符串。
        /// </summary>
        public static string OnlyEnterNumOrLetter {
            get {
                return ResourceManager.GetString("OnlyEnterNumOrLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码有效日期 的本地化字符串。
        /// </summary>
        public static string PasswordExprityDate {
            get {
                return ResourceManager.GetString("PasswordExprityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入同权限人帐号或者用户角色 的本地化字符串。
        /// </summary>
        public static string PlearsEnterEquelPrivilegeUserIDOrRoleID {
            get {
                return ResourceManager.GetString("PlearsEnterEquelPrivilegeUserIDOrRoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍卡器类型 的本地化字符串。
        /// </summary>
        public static string ReaderType {
            get {
                return ResourceManager.GetString("ReaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请重新登录！ 的本地化字符串。
        /// </summary>
        public static string ReLogin {
            get {
                return ResourceManager.GetString("ReLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效性 的本地化字符串。
        /// </summary>
        public static string StatusFlag {
            get {
                return ResourceManager.GetString("StatusFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号 的本地化字符串。
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户已存在 的本地化字符串。
        /// </summary>
        public static string UserIDExist {
            get {
                return ResourceManager.GetString("UserIDExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string UserMaster {
            get {
                return ResourceManager.GetString("UserMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
