//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rdp.Resources.Globalization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResVersion2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResVersion2() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rdp.Resources.Globalization.ResVersion2", typeof(ResVersion2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /Ajax/CodeTable/GetCodeTable.ashx?v=2020&amp;tableName= 的本地化字符串。
        /// </summary>
        public static string ComboboxUrl {
            get {
                return ResourceManager.GetString("ComboboxUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;../../css/plugin/validate.extend.css&quot; /&gt; 的本地化字符串。
        /// </summary>
        public static string CPValidateExtendCss {
            get {
                return ResourceManager.GetString("CPValidateExtendCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;/HttpCombiner.ashx?s=css&amp;t=text/css&amp;v=cou20123&quot; /&gt; 的本地化字符串。
        /// </summary>
        public static string Css {
            get {
                return ResourceManager.GetString("Css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;link href=&quot;../../Css/crmbase.css&quot; rel=&quot;stylesheet&quot; /&gt; 的本地化字符串。
        /// </summary>
        public static string CssCrmbase {
            get {
                return ResourceManager.GetString("CssCrmbase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;link rel=&quot;Stylesheet&quot; type=&quot;text/css&quot; href=&quot;../../css/css_all.css&quot; /&gt; 的本地化字符串。
        /// </summary>
        public static string CssCss_all {
            get {
                return ResourceManager.GetString("CssCss_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;link rel=&quot;Stylesheet&quot; type=&quot;text/css&quot; href=&quot;../../css/normal.css&quot; /&gt; 的本地化字符串。
        /// </summary>
        public static string CssNormal {
            get {
                return ResourceManager.GetString("CssNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;../../css/table_blue.css&quot; /&gt; 的本地化字符串。
        /// </summary>
        public static string CssTable_blue {
            get {
                return ResourceManager.GetString("CssTable_blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script type=&quot;text/javascript&quot; src=&quot;/HttpCombiner.ashx?s=javascript&amp;t=type/javascript&amp;v=cou36066&quot;&gt;&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string Javascript {
            get {
                return ResourceManager.GetString("Javascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /HttpCombiner.ashx?s=javascript&amp;t=type/javascript&amp;v=cou31569&amp;ex= 的本地化字符串。
        /// </summary>
        public static string JavascriptWithEx {
            get {
                return ResourceManager.GetString("JavascriptWithEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script type=&quot;text/javascript&quot; src=&quot;../../js/plugin/jquery.js&quot;&gt;&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string JPJqueryJs {
            get {
                return ResourceManager.GetString("JPJqueryJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script type=&quot;text/javascript&quot; src=&quot;../../js/plugin/jquery.validate.js&quot;&gt;&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string JPJqueryValidateJs {
            get {
                return ResourceManager.GetString("JPJqueryValidateJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script type=&quot;text/javascript&quot; src=&quot;../../js/plugin/QueryPage.js&quot;&gt;&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string JPQueryPageJs {
            get {
                return ResourceManager.GetString("JPQueryPageJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script src=&quot;../../js/plugin/validate.extend-1.0.1.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string JPValidateExtendJs {
            get {
                return ResourceManager.GetString("JPValidateExtendJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script src=&quot;../../js/common.js&quot;&gt;&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string JsCommon {
            get {
                return ResourceManager.GetString("JsCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script src=&quot;../../js/commonCardPrint.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string JsCommonCardPrint {
            get {
                return ResourceManager.GetString("JsCommonCardPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script type=&quot;text/javascript&quot; src=&quot;../../js/jquery-1.7.2.js&quot;&gt;&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string JsJquery_172 {
            get {
                return ResourceManager.GetString("JsJquery_172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script type=&quot;text/javascript&quot; src=&quot;../../js/Place.js&quot;&gt;&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string JsPlace {
            get {
                return ResourceManager.GetString("JsPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script type=&quot;text/javascript&quot; src=&quot;/Res/My97DatePicker/WdatePicker.js?t=123456783&quot;&gt;&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string MyDatePicker {
            get {
                return ResourceManager.GetString("MyDatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;object id=&quot;MIF&quot; width=&quot;0&quot; height=&quot;0&quot; classid=&quot;CLSID:7BEC3845-30E9-11D6-BB52-00D0096A436E&quot;&gt;
        ///        &lt;param name=&quot;COM&quot; /&gt;
        ///        &lt;param name=&quot;SECTOR&quot; value=&quot;1&quot; /&gt;
        ///        &lt;param name=&quot;BLOCK&quot; value=&quot;0&quot; /&gt;
        ///    &lt;/object&gt;
        ///    &lt;script type=&quot;text/vbscript&quot;&gt;
        ///    DIM s
        ///    s = 1
        ///    // readeropen()
        ///    Sub RC()
        ///        DIM a, b, s2, str
        ///        s2 = s
        ///        a = &quot;&quot;
        ///        b = &quot;&quot;
        ///        call MIF.MIFAREREADSERIAL()
        ///        s = MIF.CAPTION
        ///        //check if the same card is placed on the reader
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ReadCard1 {
            get {
                return ResourceManager.GetString("ReadCard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;object id=&quot;rd&quot; codebase=&quot;/Bin/comRD800.dll&quot; classid=&quot;clsid:638B238E-EB84-4933-B3C8-854B86140668&quot; style=&quot;display: none;&quot;&gt;&lt;/object&gt; 的本地化字符串。
        /// </summary>
        public static string ReadCard3 {
            get {
                return ResourceManager.GetString("ReadCard3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script src=&quot;../../Res/easyui-extend-1.1.1/validate-extend.js&quot;&gt;&lt;/script&gt; 的本地化字符串。
        /// </summary>
        public static string REValidateExtendJs {
            get {
                return ResourceManager.GetString("REValidateExtendJs", resourceCulture);
            }
        }
    }
}
